repos:
  - repo: https://github.com/psf/black
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.11
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5
    hooks:
      - id: ruff
        args: ["--fix"]
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pytest -q
        language: system
        pass_filenames: false
      - id: update-status
        name: update-progress
        entry: python scripts/update_status.py
        language: system
        pass_filenames: false
      - id: auto-summarize
        name: summarize-and-rebuild
        entry: bash -c 'echo "Paste chat then Ctrl-D:"; cat | python scripts/summarize_chat.py --stdin --manual && python scripts/retrieve_context.py rebuild && python scripts/update_status.py'
        language: system
        pass_filenames: false 
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.8
    hooks:
      - id: bandit
        args: ["-q", "-ll", "-r", "scripts", "tests"]
  - repo: https://github.com/trufflesecurity/trufflehog.git
    rev: v3.68.5
    hooks:
      - id: trufflehog
        name: secret-scan
        entry: trufflehog filesystem --no-update --fail --json .
        language: system
        pass_filenames: false 