# Trigger: 2024-06-09 – Forcing workflow reload to ensure latest ruff command is used
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run linters
        run: |
          ruff check .
      - name: Run mypy
        run: |
          mypy scripts tests
      - name: Run pip-audit
        run: |
          pip-audit --strict
      - name: Run tests
        run: pytest --cov=./ --cov-fail-under=90 -q 