name: performance-benchmark

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  bench:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run benchmark
        run: python scripts/benchmark_performance.py --chunks 10000
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: performance-benchmark
          path: benchmarks/benchmark_10000.json
          retention-days: 7 