name: weekly-openai-smoke

on:
  schedule:
    - cron: '0 4 * * 1'  # Monday 04:00 UTC
  workflow_dispatch:
permissions:
  contents: read

jobs:
  openai-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run OpenAI summarization smoke test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          echo "Hello world from real OpenAI" | python scripts/summarize_chat.py --stdin 